# Generated by Django 3.1.5 on 2021-01-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('mail_id', models.EmailField(max_length=30)),
                ('entrydate', models.DateField()),
                ('age', models.IntegerField()),
                ('contact', models.IntegerField()),
            ],
            options={  
                'db_table': 'employee', 
            },
        ),
    ]
