# Generated by Django 3.1.5 on 2021-01-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210128_1450'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='workers',
            table=None,
        ),
    ]
